# Manual started workflow
name: e2e-complex-auto
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.RECORDING_KEY }}
      CYPRESS_username: ${{ secrets.CYPRESS_USER_NAME }}
      CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASEURL }}
      CYPRESS_host: ${{ secrets.CYPRESS_HOST }}
      CYPRESS_ENVIRONMENT: ${{ github.base_ref }}
      CYPRESS_authRealm: ${{ secrets.CYPRESS_AUTH_REALM }}
      CYPRESS_authClientId: ${{ secrets.CYPRESS_AUTH_CLIENT_ID }}
      CYPRESS_authUrl: ${{ secrets.CYPRESS_AUTH_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the PR branch
      - name: Checkout Target Branch
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list          

      - name: Wait for API response
        env:
          url: ${{ secrets.CYPRESS_API_HOST }}
          code: 200
          wait_time: 10
          max_attempts: 5
        run: |
          cd tool-guidance/testing
          chmod +x waitforconnection.sh
          bash ./waitforconnection.sh          

      - name: Wait for APP response
        env:
          url: ${{ secrets.CYPRESS_HOST }}
          code: 200
          wait_time: 10
          max_attempts: 5
        run: |
          cd tool-guidance/testing
          chmod +x waitforconnection.sh
          bash ./waitforconnection.sh   

      - name: E2E Smoke tests
        uses: cypress-io/github-action@v5
        # let's give this action an ID so we can refer
        # to its output values later
        id: smoke
        continue-on-error: false
        with:
          wait-on: ${{ secrets.CYPRESS_HOST }}
          wait-on-timeout: 120
          record: true
          install-command: npm ci -f
          working-directory: tool-guidance/testing
          browser: chrome
          ci-build-id: ${{ github.event.number }}

      - name: Print Env Vars
        run: |
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Change ID: ${{ github.event.number }}
          echo Cypress BaseUrl: $CYPRESS_BASE_URL
          echo Cypress Host: $CYPRESS_HOST
          echo Cypress Host: $CYPRESS_ENVIRONMENT
          echo Keycloak Authorization Realm: $CYPRESS_authRealm
          echo Keycloak Authorization Client ID: $CYPRESS_authClientId
          echo Keycloak Authorization URL: $CYPRESS_authUrl
